### ISSUE TITLE
Bug fixex

### ISSUE THREAD

**Issue by ats1999** [ats1999/md-byte#19]
- [x] https://github.com/nhn/tui.editor/issues/1767
- [ ] https://github.com/nhn/tui.editor/issues/1766
- [x] https://github.com/nhn/tui.editor/issues/1763
- [x] https://github.com/nhn/tui.editor/issues/1761
- [ ] https://github.com/nhn/tui.editor/issues/1758

**Comment by ats1999** [comment]
Use this to fix part of toolbar hidden...
```css
@media only screen and (max-width: 700px) {
    .toastui-editor-dropdown-toolbar {
        max-width: none;
        flex-wrap: wrap;
        height: fit-content;
    }
}
```
